name: Tests
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer install --no-interaction
      - run: composer run verify
