name: Tests
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.2'
          - '8.3'
          - '8.4'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer install --no-interaction
      - run: composer run verify
